sudo: required
jdk:
- oraclejdk8
language: groovy
services:
- docker
before_install:
- docker pull centos:7
install: gradle clean check
script:
- gradle assemble build myZip
after_success:
- docker --version
- docker build -t elakkad/dockertest:latest .
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push elakkad/dockertest:latest
deploy:
- provider: bintray
  user: "$BINTRAY_USER"
  file: ".descriptor.json"
  key: "$BINTRAY_API_KEY"
  skip_cleanup: true
  overwrite: true
  on:
    all_branches: true
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  local_dir: build/distributions
  skip_cleanup: true
  on:
    tags: true
  bucket: traviscis3bucket
  region: us-west-2
  wait-until-deploy: true
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: traviscis3bucket
  key: dockerExperiment.zip
  bundle_type: zip
  application: TravisCICodeDeployApp
  deployment_group: TravisCIAutoScalingGroupName
  region: us-west-2
  wait-until-deploy: true
  on:
    tags: true
env:
  global:
  - secure: fSUu6LU/2tEkW9G4jftJMILzQv7rg1Kp0O0XPqeCFO3EtDNEJU2OvHRlt3Hs6sa9gLqACdt3zlkfsg9p44viNYtR93rcLMabXaF5mR0EO/NaLpKoa+830rleJl0IKX2OTqL4CY8W7uMLKd07Uwpv3y1rz16dnQsltuRYGaIAjG6/XS20bwCUXa1jEGpgmV1FeIEgR55UerchXeVBhajxluVuyhzJjReC5vR9tutlcMhz9IuUgWE3ktZyHUIs0pi45qjOmMeDf48zGv2GT/Dyxqc8O9JnjHM3vciYcbe5vVKHlmUC47xSpBRhqW5oUoiNYwfSsuprQO0+QXFkUsKQJabdO+6RziR46NaUDW2FLkJXgSDs3xyhFZ27xbjIim1nEOQEIRKVZPNkUiiWsP2r8fMqyBKnEbpFgnINJa+RTjsXEqTZ5uMVIo8rWOAumssvbx8iiot0i5GosdZr3NidzOsk68eoW5QWXzprliKAJdIE8xF8XU5h1k1sgPV3CC+smZxtzcp77FWzmD8DPW63IpyX+r3YE5QH+kfoEhYZhPRxR/nqE5Jcru1zGR9e2+2ukCZK9aldMI14oHuOgvdnBmmYEOsUfFG1G2u78sjZ/b+2k66eQaij8LWWLD0gkIr3mrFVLVbXdjieFYQNUgQsk2hJ6djb5iuNhSIJHIaQdOo=
notifications:
  slack:
    secure: jWG0AeIdBgSdJobLRM3DK930o1VLUEXT2ZsISWeAbkyr8qhbIPDkg/2AJSRm9veZGFktTk33jYidvOFQtKezo/TuIE2vFvLld5+imMDtr89GDIVZlDlAf2l0d9Xe2uVLzzkqBvDUWgsyIRXnhLXGj5tsirO4KG6ubLBv0xxziBA96q0AlU/pii9/VcV1Pc/jstCrF9boJq+BlLNh65xTuQChADRYbyAp391GEtGyP+L5dGy+NkYR5GE5DVLXq5z9QIA8YuYylrY8IqwBhyu6jtWi1POg3vPIZy4PdLcGuf6mH6d9AdjxWvIRFO+8uKALVJpDHK3LX63Y0zzkJbOcdfTmF4oFocMFxnXYLz5Qx9M3ERJ/fLkRbcX7XRiBD2yzhXyZ0TN0OJMVxVJpJeayHU/2E6dJfvOaAqRws4DsiHj9yReCXrpHhyDAygcMttxarUAwBRNG/joIUMMuuz281lT2S8De6o7lxXNc/WxKOCiUqAfA09kiEFZyDDwfTipbGvQynUSV3P+jNpJ37YUr0C6Z/lx+50AyW1Ic6vE3KqwJpcI9N7k6KHNzUKMFx07DhUZwYrSU6B/P80DtnHPKSyYGOrN6alt58V1YpSwd5kuRDubMG7SZHoPbFUf+c7wmjt6EIiuuk9u2dR/nl4Yr1Pfk7B6b34oveX7G0IIgq3I=
  on_success: change
  on_failure: always
  on_start: always
  on_pull_requests: true
