# http://travis-encrypt.github.io/
# http://lint.travis-ci.org/

sudo: required

language: java

services:
  - docker
  
before_install:
   - docker pull centos:7
   - docker build -t elakkad/dockertest .
   
env:
  global:
   - secure: eM5F0l7f96qf/jbVmWbAXZrGnXVbUL3hQxct/nMxiMekgs0tN3m3pxsbJYsZ7WgPGta786tT0Z03ZLz15BDKl66067KCGLDRp+yOV2csQJllu/97OkFF3e5oGww7U8VIOf2jxLBCN+8mlu2l75YkJDh4Ikf1wp4cLP378vWBKdoQuDk5e66DUMoePgUUI9n1ju51c4Rx4PF/7Kqr/+d471Sml361/s0PStVZVB8+wItOZu3s5b6+vgk2bX2S9Ut3pRS7o9Etty68vB8ZcxSWmaj4Le9/tYKGQp2HXeqygWyALBQpaa9GYZVm+IHuaWQi3fMOURKRlQWvfqOxtb57umYXjfDVPJ5ZTVGVzwv7gw4kHP7Ffvi2N2ESphQoO9wXj6gmA5t4YJ/9tSI06ywcBaCx1aT30UF6m9u2x+xLZmGrjcR9WhYF321k+OBM6EQz6BeXYmVgsDlLklZD5e7DZ1uCJWON0rmMZnUffni9CtuaNLexDK6M/A/s72SU0SMKvDwAnbEn+eB9SpJ5naevTzyunaA7yYCLR4+ID5zfLBUVXG/v2imws1RcjZh72IEE6LLXZc6byp1cUnZ0GuHvpoU7o1PZdqMjL9wekX8NHwbakoelB9u8H52svPRccl+WIvoN5hmCQCgOJnvTcIL18Z7T7f5mYrxYAvivyRW7OlQ=
