# http://travis-encrypt.github.io/
# http://lint.travis-ci.org/

sudo: required

language: java

services:
  - docker
  
before_install:
   - docker pull centos:7
   - docker build -t elakkad/dockertest .
