os: linux
files:
  - source: icpweb/dockerExperiment.zip
    destination: /root/dockerExperiment.zip

version: 0.0
os: linux
files:
  - source: /dockerExperiment.jar
    destination: /var/deployments/
hooks:
  BeforeInstall:
    - location: change_permissions
      timeout: 300
      runas: root
    - location: run_java_minus_jar
      timeout: 300
      runas: root
  ApplicationStop:
    - location: check_on_processes
      timeout: 300
      runas: root
