version: 0.0
os: linux
files:
  - source: /
    destination: /var/deployments/
hooks:
  ApplicationStop:
    - location: applicationStopInstanceTerminate.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: beforeInstall1.sh
      timeout: 300
      runas: root
    - location: beforeInstall2.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: appStart.sh
      timeout: 300
      runas: root
ValidateService:
    - location: validateApp.sh
      timeout: 300
      runas: root
